### ISSUE TITLE
Change output file names based on telemetry type

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/telemetry-injector#1]
Output should be named appropriately, and follow same naming convention trail maker video file output, however should end with either `-camm` or `-gpmd` depending on the setting used.

**Comment by karamvirup** [comment]
@himynamesdave generated video has name`metadata-video.mp4` please see that, you want to change it?

**Comment by karamvirup** [comment]
changed to allow user to select the name of their video as they wish.

**Comment by himynamesdave** [comment]
@karamvirup I like your implementation idea but currently get an error

```
python3 telemetry-injector.py -c -i UKBC003-in/ -o UKBC003-out-camm/
Output file already exists.
```

**Comment by karamvirup** [comment]
@himynamesdave 

https://github.com/trek-view/telemetry-injector/issues/1#issuecomment-1315697858

https://github.com/trek-view/telemetry-injector/blob/dep/README.md
